{{- if and .Values.bullExporter.enabled .Values.bullExporter.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "soketi.fullname" . }}-bullmq-exporter
  labels:
    {{- include "soketi.bullExporterLabels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "soketi.bullExporterSelectorLabels" . | nindent 6 }}
  endpoints:
    - port: bull-metrics
      interval: {{ .Values.bullExporter.serviceMonitor.scrapeInterval }}
      scrapeTimeout: {{ .Values.bullExporter.serviceMonitor.scrapeTimeout }}
{{- end }}
