{{- if and .Values.bullExporter.enabled .Values.bullExporter.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "soketi.serviceAccountName" . }}-bullmq-exporter
  labels:
    {{- include "soketi.bullExporterLabels" . | nindent 4 }}
  {{- with .Values.bullExporter.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
