{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "soketi.fullname" . }}-metrics
  labels:
    {{- include "soketi.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9601
      targetPort: 9601
      protocol: TCP
      name: metrics
  selector:
    {{- include "soketi.selectorLabels" . | nindent 4 }}
{{- end }}
